pipelines:    
  live_encoder:
    type: subprocess
    template: >
      v4l2src device=$video_device io-mode=2 !
      mpph265enc 
        header-mode=1 
        bps=$bps 
        gop=1 !
      rndbuffersize min=1380 max=1380 !
      multiudpsink 
        clients=$udp_clients
        auto-multicast=$auto_multicast
        async=true 
        sync=false
        qos=true
    params:
      video_device: /dev/video31
      font_size: 24
      bps: 3000
      gop: 30
      udp_clients: "127.0.0.1:5555,127.0.0.1:5556,127.0.0.1:5557"
      auto_multicast: false
    description: 实时视频编码推流

  live_encoder_tee:
    type: subprocess
    template: >
      v4l2src device=$video_device io-mode=2 !
      video/x-raw,format=NV12,width=640,height=512,framerate=30/1 !
      tee name=t 
        t. ! queue !
        mpph265enc header-mode=1 bps=$bps gop=1 rc-mode=2 !
        rndbuffersize min=1380 max=1380 !
        multiudpsink 
          clients=$udp_clients
          auto-multicast=$auto_multicast
          async=true 
          sync=false
        t. ! queue name=proc_queue max-size-buffers=1 leaky=downstream !
        videoconvert !
        video/x-raw,format=BGR,width=640,height=512,framerate=30/1 ! 
        appsink name=proc emit-signals=true max-buffers=3 drop=true
    params:
      bps: 1000000
      udp_clients: "127.0.0.1:5555,127.0.0.1:5556,127.0.0.1:5557"
      auto_multicast: false
    description: 实时视频编码推流

  storage_splitvideo:
    type: gst
    template: >
      udpsrc address=$host port=$port !
      h265parse !
      mppvideodec arm-afbc=false !
      videoconvert !
      videorate !
      video/x-raw,framerate=$fps !
      mpph265enc bps=$bps !
      h265parse !
      splitmuxsink name=muxer 
        muxer-factory=matroskamux
        max-size-time=$segment_duration
        max-files=$max_files
        async-finalize=true
        location=$output_path
    params:
      host: "127.0.0.1"
      port: 6633
      bps: 3000000
      fps: 30
      max_files: 10
      segment_duration: 10000000000
      output_path: video_%04d.mkv
    description: 分片录像

  storage_singleframe:
    type: subprocess
    template: >
      udpsrc address=$host port=$port !
      h265parse !
      mppvideodec arm-afbc=false !
      videoconvert !
      videorate drop-only=true !
      video/x-raw,framerate=$fps !
      mppjpegenc !
      multifilesink max-files=$max_files location=$output_path
    params:
      host: "127.0.0.1"
      port: 8833
      fps: 1/1
      max_files: 10
      output_path: frame%04d.jpg
    description: 高清图像

  live_det_encoder:
    type: gst
    template: >
      appsrc name=proc_encoder is-live=true format=time block=false
        caps=video/x-raw,format=BGR,width=640,height=512,framerate=30/1 !
      videoconvert !
      video/x-raw,format=NV12,width=640,height=512,framerate=30/1 !
      mpph265enc 
        header-mode=1
        bps=$bps 
        gop=1 !
      rndbuffersize min=1380 max=1380 !
      multiudpsink 
        clients=$udp_clients
        auto-multicast=$auto_multicast
        async=true 
        sync=false
        qos=true
    params:
      bps: 3000000
      udp_clients: "127.0.0.1:55551"
      auto_multicast: false
    description: 实时目标检测编码推流
  
