pipelines:
  live_encoder:
    type: gst
    template: >
      videotestsrc pattern=smpte is-live=true !
      video/x-raw,format=NV12,width=2048,height=2048,framerate=30/1 !
      videoconvert !
      textoverlay 
        text="+"
        font-desc=$fontdesc
        halignment=center
        valignment=center
        color=0xFFFFFFFF
        shaded-background=false !
      videoconvert !
      video/x-raw,format=NV12,width=2048,height=2048,framerate=30/1 !
      videoflip method=$videoflip_1 !
      videoflip method=$videoflip_2 !
      mpph265enc header-mode=1 gop=1 bps=$bps !
      rndbuffersize min=1380 max=1380 !
      multiudpsink
        clients=$udp_clients
        sync=false
        async=false
        auto-multicast=false
    params:
      raw_fps: 30
      bps: 40000000
      fontdesc: Sans UltraCondensed 0
      videoflip_1: none
      videoflip_2: none
      udp_clients: 192.168.137.1:23451, 127.0.0.1:5556, 127.0.0.1:5557
    description: 实时视频编码推流

  live_det_encoder:
    type: gst
    template: >
      videotestsrc pattern=smpte is-live=true !
      video/x-raw,format=NV12,width=2048,height=2048,framerate=30/1 !
      multiqueue max-size-buffers=1 max-size-bytes=0 max-size-time=0 !
      tee name=t
        t. ! queue max-size-buffers=1 leaky=downstream !
          videoconvert !
          cairooverlay name=ovl !
          textoverlay 
            text="+"
            font-desc=$fontdesc
            halignment=center
            valignment=center
            color=0xFFFFFFFF
            shaded-background=false !
          videoconvert !
          video/x-raw,format=NV12,width=2048,height=2048,framerate=30/1 !
          videoflip method=$videoflip_1 !
          videoflip method=$videoflip_2 !
          mpph265enc header-mode=1 gop=1 bps=$bps !
          rndbuffersize min=1380 max=1380 !
          multiudpsink
            clients=$udp_clients
            sync=false
            async=false
            auto-multicast=false
        t. ! queue max-size-buffers=1 leaky=downstream !
          videocrop top=$top bottom=$bottom left=$left right=$right !
          videoconvert !
          video/x-raw,format=RGB,width=$crop_width,height=$crop_height,framerate=30/1 !
          appsink
            name=vis_det
            sync=false
            emit-signals=true
            max-buffers=1
            drop=true
    params:
      raw_fps: 30
      bps: 40000000
      top: 704
      bottom: 704
      left: 704
      right: 704
      crop_width: 640
      crop_height: 640
      fontdesc: Sans UltraCondensed 0
      videoflip_1: none
      videoflip_2: none
      udp_clients: 192.168.137.1:23451, 127.0.0.1:5556, 127.0.0.1:5557
    description: 带目标检测实时视频编码推流

  storage_splitvideo:
    type: subprocess
    template: >
      udpsrc address=$host port=$port !
      h265parse !
      splitmuxsink name=muxer 
        muxer-factory=matroskamux
        max-size-time=$segment_duration
        max-files=$max_files
        async-finalize=true
        location=$output_path
    params:
      host: "127.0.0.1"
      port: 3366
      max_files: 1
      segment_duration: 5000000000
      output_path: video_%02d.mkv
    description: 分片录像

  storage_singleframe:
    type: subprocess
    template: >
      udpsrc address=$host port=$port !
      h265parse !
      mppvideodec arm-afbc=false !
      videorate drop-only=true !
      video/x-raw,framerate=$fps !
      mppjpegenc !
      multifilesink max-files=$max_files location=$output_path
    params:
      host: "127.0.0.1"
      port: 3388
      fps: 1/30
      max_files: 1
      output_path: frame_%04d.jpg
    description: 高清图像